"""Render the shared schema registry into per-warehouse DDL and load schemas.

Outputs, all regenerated from scratch on every run:

* ``sql/redshift_init.sql``            — schemas + tables for ``bootstrap_redshift.sh``
* ``sql/bigquery_init.sql``            — tables for ``bootstrap_bigquery.sh``
* ``sql/bq_schemas/<schema>.<table>.json`` — ``bq load --schema`` payloads

Never edit those files by hand; edit ``schema/registry.py`` and re-run:

    python scripts/generate_ddl.py
"""

from __future__ import annotations

import json
import logging
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from schema.registry import (  # noqa: E402  (path setup must precede the import)
    Column,
    LogicalType,
    Table,
    all_tables,
    raw_schemas,
)

logger = logging.getLogger(__name__)

GENERATED_BANNER = "-- GENERATED by scripts/generate_ddl.py from schema/registry.py — do not edit."


# ---------------------------------------------------------------------------
# Redshift
# ---------------------------------------------------------------------------

REDSHIFT_TYPES = {
    "int": "INTEGER",
    "bool": "BOOLEAN",
    "date": "DATE",
    "timestamp": "TIMESTAMP",
}

# Encoding follows from the type: AZ64 is Redshift's integer-optimised encoding,
# booleans are too narrow for compression to pay off, everything else takes ZSTD.
REDSHIFT_ENCODINGS = {"int": "AZ64", "bool": "RAW"}


def redshift_type(logical: LogicalType) -> str:
    if logical.kind == "string":
        return f"VARCHAR({logical.length})"
    if logical.kind == "decimal":
        return f"NUMERIC({logical.precision},{logical.scale})"
    if logical.kind not in REDSHIFT_TYPES:
        raise ValueError(f"No Redshift type for logical kind {logical.kind!r}")
    return REDSHIFT_TYPES[logical.kind]


def redshift_distribution(table: Table) -> str:
    if table.distribution.style != "KEY":
        return f"DISTSTYLE {table.distribution.style};"
    clause = f"DISTSTYLE KEY DISTKEY ({table.distribution.key})"
    if table.distribution.sort_key is None:
        return f"{clause};"
    return f"{clause} SORTKEY ({table.distribution.sort_key});"


def redshift_columns(columns: tuple[Column, ...]) -> list[str]:
    name_width = max(len(column.name) for column in columns) + 2
    type_width = max(len(redshift_type(column.type)) for column in columns) + 2
    rendered = []
    for column in columns:
        encoding = REDSHIFT_ENCODINGS.get(column.type.kind, "ZSTD")
        rendered.append(
            f"    {column.name:<{name_width}}{redshift_type(column.type):<{type_width}}ENCODE {encoding}"
        )
    return rendered


def render_redshift() -> str:
    lines = [
        "-- =====================================================================",
        "-- Redshift initialization for the Banking demo",
        "-- =====================================================================",
        GENERATED_BANNER,
        "--",
        "-- Creates the raw schemas and source tables that mirror the CSV seeds in",
        "-- dbt/seeds/raw_*/. Columns match the CSV headers in order, so the COPY",
        "-- commands generated by scripts/redshift/load_to_redshift.sh can load",
        "-- straight from S3 without column lists.",
        "--",
        "-- Encoding favours ZSTD for VARCHAR/NUMERIC/DATE/TIMESTAMP and AZ64 for",
        "-- INTEGER. Distribution defaults to AUTO; small lookups use ALL and",
        "-- high-volume fact tables use KEY distribution with a SORTKEY on the",
        "-- natural time column.",
        "-- =====================================================================",
        "",
        "-- ---------------------------------------------------------------------",
        "-- Schemas",
        "-- ---------------------------------------------------------------------",
    ]
    for schema in raw_schemas():
        lines.append(f"DROP SCHEMA IF EXISTS {schema} CASCADE;")
        lines.append(f"CREATE SCHEMA {schema};")
        lines.append("")

    current_schema = ""
    for table in all_tables():
        if table.schema != current_schema:
            lines.extend(
                [
                    "",
                    "-- =====================================================================",
                    f"-- {table.schema}",
                    "-- =====================================================================",
                    "",
                ]
            )
            current_schema = table.schema
        lines.append(f"-- {table.name}")
        lines.append(f"CREATE TABLE {table.schema}.{table.name} (")
        lines.append(",\n".join(redshift_columns(table.columns)))
        lines.append(")")
        lines.append(redshift_distribution(table))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# BigQuery
# ---------------------------------------------------------------------------

BIGQUERY_TYPES = {
    "string": "STRING",
    "int": "INT64",
    "bool": "BOOL",
    "date": "DATE",
    "timestamp": "TIMESTAMP",
}


def bigquery_type(logical: LogicalType) -> str:
    """Concrete BigQuery type.

    Strings drop their Redshift length: BigQuery's parameterised STRING(n)
    rejects the whole load job on an over-length value, and the length carries
    no analytical meaning here.
    """
    if logical.kind == "decimal":
        return f"NUMERIC({logical.precision}, {logical.scale})"
    if logical.kind not in BIGQUERY_TYPES:
        raise ValueError(f"No BigQuery type for logical kind {logical.kind!r}")
    return BIGQUERY_TYPES[logical.kind]


def render_bigquery() -> str:
    lines = [
        "-- =====================================================================",
        "-- BigQuery initialization for the Banking demo",
        "-- =====================================================================",
        GENERATED_BANNER,
        "--",
        "-- Creates the raw source tables that mirror the CSV seeds in",
        "-- dbt/seeds/raw_*/. Columns match the CSV headers in order.",
        "--",
        "-- Datasets are created separately by scripts/bigquery/bootstrap_bigquery.sh,",
        "-- which needs to pin their location. Table names are left unqualified so",
        "-- the script's --project_id supplies the project.",
        "--",
        "-- CREATE OR REPLACE makes re-running safe without dropping datasets. There",
        "-- are no distribution styles or sort keys: BigQuery clusters automatically",
        "-- and these volumes do not warrant explicit partitioning.",
        "-- =====================================================================",
        "",
    ]

    current_schema = ""
    for table in all_tables():
        if table.schema != current_schema:
            lines.extend(
                [
                    "-- =====================================================================",
                    f"-- {table.schema}",
                    "-- =====================================================================",
                    "",
                ]
            )
            current_schema = table.schema
        width = max(len(column.name) for column in table.columns) + 2
        lines.append(f"CREATE OR REPLACE TABLE `{table.schema}.{table.name}` (")
        lines.append(
            ",\n".join(
                f"    {column.name:<{width}}{bigquery_type(column.type)}"
                for column in table.columns
            )
        )
        lines.append(");")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# bq load schemas
# ---------------------------------------------------------------------------

BQ_SCHEMA_TYPES = {
    "string": "STRING",
    "int": "INT64",
    "bool": "BOOL",
    "date": "DATE",
    "timestamp": "TIMESTAMP",
    "decimal": "NUMERIC",
}


def bq_schema_field(column: Column) -> dict[str, str]:
    """One entry of a ``bq load --schema`` JSON payload.

    Every column is NULLABLE: the seed CSVs carry ``\\N`` for missing values and
    the demo has no not-null guarantees at the raw layer.
    """
    if column.type.kind not in BQ_SCHEMA_TYPES:
        raise ValueError(f"No bq load type for logical kind {column.type.kind!r}")
    field = {
        "name": column.name,
        "type": BQ_SCHEMA_TYPES[column.type.kind],
        "mode": "NULLABLE",
    }
    if column.type.kind == "decimal":
        # Sent as strings: the REST TableFieldSchema types these as int64.
        field["precision"] = str(column.type.precision)
        field["scale"] = str(column.type.scale)
    return field


def write_bq_schemas(target_dir: Path) -> int:
    for stale in target_dir.glob("*.json"):
        stale.unlink()
    for table in all_tables():
        fields = [bq_schema_field(column) for column in table.columns]
        destination = target_dir / f"{table.schema}.{table.name}.json"
        destination.write_text(json.dumps(fields, indent=2) + "\n", encoding="utf-8")
    return len(all_tables())


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    sql_dir = PROJECT_ROOT / "sql"
    schemas_dir = sql_dir / "bq_schemas"
    schemas_dir.mkdir(parents=True, exist_ok=True)

    (sql_dir / "redshift_init.sql").write_text(render_redshift(), encoding="utf-8")
    logger.info("wrote sql/redshift_init.sql")

    (sql_dir / "bigquery_init.sql").write_text(render_bigquery(), encoding="utf-8")
    logger.info("wrote sql/bigquery_init.sql")

    logger.info("wrote %d schemas under sql/bq_schemas/", write_bq_schemas(schemas_dir))

    columns = sum(len(table.columns) for table in all_tables())
    logger.info("Done. %d tables, %d columns.", len(all_tables()), columns)


if __name__ == "__main__":
    main()
