-- =====================================================================
-- BigQuery initialization for the Banking demo
-- =====================================================================
-- GENERATED by scripts/generate_ddl.py from schema/registry.py — do not edit.
--
-- Creates the raw source tables that mirror the CSV seeds in
-- dbt/seeds/raw_*/. Columns match the CSV headers in order.
--
-- Datasets are created separately by scripts/bigquery/bootstrap_bigquery.sh,
-- which needs to pin their location. Table names are left unqualified so
-- the script's --project_id supplies the project.
--
-- CREATE OR REPLACE makes re-running safe without dropping datasets. There
-- are no distribution styles or sort keys: BigQuery clusters automatically
-- and these volumes do not warrant explicit partitioning.
-- =====================================================================

-- =====================================================================
-- raw_core_banking
-- =====================================================================

CREATE OR REPLACE TABLE `raw_core_banking.customers` (
    customer_id          STRING,
    first_name           STRING,
    last_name            STRING,
    email                STRING,
    phone                STRING,
    ssn                  STRING,
    tax_id               STRING,
    date_of_birth        DATE,
    customer_segment     STRING,
    customer_type        STRING,
    branch_id            STRING,
    primary_employee_id  STRING,
    kyc_status           STRING,
    risk_band            STRING,
    created_at           TIMESTAMP,
    updated_at           TIMESTAMP
);

CREATE OR REPLACE TABLE `raw_core_banking.customer_addresses` (
    address_id      STRING,
    customer_id     STRING,
    address_type    STRING,
    address_line_1  STRING,
    address_line_2  STRING,
    city            STRING,
    state           STRING,
    postal_code     STRING,
    country         STRING,
    is_primary      BOOL,
    effective_from  DATE,
    effective_to    DATE
);

CREATE OR REPLACE TABLE `raw_core_banking.customer_contacts` (
    contact_id     STRING,
    customer_id    STRING,
    contact_type   STRING,
    contact_value  STRING,
    is_primary     BOOL,
    is_verified    BOOL,
    opt_out        BOOL,
    added_at       TIMESTAMP
);

CREATE OR REPLACE TABLE `raw_core_banking.branches` (
    branch_id            STRING,
    branch_name          STRING,
    address_line_1       STRING,
    city                 STRING,
    state                STRING,
    postal_code          STRING,
    country              STRING,
    region               STRING,
    phone                STRING,
    manager_employee_id  STRING,
    opened_date          DATE,
    closed_date          DATE,
    is_active            BOOL
);

CREATE OR REPLACE TABLE `raw_core_banking.employees` (
    employee_id       STRING,
    first_name        STRING,
    last_name         STRING,
    email             STRING,
    phone             STRING,
    hire_date         DATE,
    termination_date  DATE,
    role              STRING,
    branch_id         STRING,
    manager_id        STRING,
    salary_band       STRING,
    is_active         BOOL
);

CREATE OR REPLACE TABLE `raw_core_banking.accounts` (
    account_id     STRING,
    customer_id    STRING,
    account_type   STRING,
    product_code   STRING,
    opened_date    DATE,
    closed_date    DATE,
    status         STRING,
    balance        NUMERIC(18, 4),
    currency       STRING,
    branch_id      STRING,
    interest_rate  NUMERIC(10, 6),
    credit_limit   NUMERIC(18, 4),
    is_joint       BOOL,
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP
);

CREATE OR REPLACE TABLE `raw_core_banking.account_holders` (
    holder_id     STRING,
    account_id    STRING,
    customer_id   STRING,
    holder_order  INT64,
    relationship  STRING,
    added_at      TIMESTAMP,
    removed_at    TIMESTAMP
);

CREATE OR REPLACE TABLE `raw_core_banking.account_types` (
    account_type_code  STRING,
    account_type_name  STRING,
    product_category   STRING
);

-- =====================================================================
-- raw_transactions
-- =====================================================================

CREATE OR REPLACE TABLE `raw_transactions.transactions` (
    transaction_id    STRING,
    account_id        STRING,
    posted_at         TIMESTAMP,
    amount            NUMERIC(18, 4),
    currency          STRING,
    transaction_type  STRING,
    merchant_id       STRING,
    description       STRING,
    is_reversal       BOOL,
    channel           STRING,
    running_balance   NUMERIC(18, 4),
    created_at        TIMESTAMP
);

CREATE OR REPLACE TABLE `raw_transactions.transaction_categories` (
    category_code   STRING,
    category_name   STRING,
    category_group  STRING,
    sign_hint       STRING
);

CREATE OR REPLACE TABLE `raw_transactions.atm_withdrawals` (
    atm_withdrawal_id      STRING,
    account_id             STRING,
    atm_terminal_id        STRING,
    atm_city               STRING,
    atm_state              STRING,
    amount                 NUMERIC(18, 4),
    fee_amount             NUMERIC(18, 4),
    withdrawn_at           TIMESTAMP,
    is_foreign             BOOL,
    network                STRING,
    parent_transaction_id  STRING
);

CREATE OR REPLACE TABLE `raw_transactions.wire_transfers` (
    wire_id                STRING,
    account_id             STRING,
    direction              STRING,
    amount                 NUMERIC(18, 4),
    currency               STRING,
    from_iban              STRING,
    to_iban                STRING,
    swift_code             STRING,
    fee_amount             NUMERIC(18, 4),
    originator_name        STRING,
    beneficiary_name       STRING,
    wire_purpose           STRING,
    sent_at                TIMESTAMP,
    status                 STRING,
    parent_transaction_id  STRING
);

CREATE OR REPLACE TABLE `raw_transactions.ach_transfers` (
    ach_id                       STRING,
    account_id                   STRING,
    direction                    STRING,
    amount                       NUMERIC(18, 4),
    ach_type                     STRING,
    counterparty_routing         STRING,
    counterparty_account_masked  STRING,
    counterparty_name            STRING,
    settled_date                 DATE,
    originated_at                TIMESTAMP,
    status                       STRING,
    sec_code                     STRING,
    return_reason_code           STRING,
    parent_transaction_id        STRING
);

-- =====================================================================
-- raw_cards
-- =====================================================================

CREATE OR REPLACE TABLE `raw_cards.card_products` (
    product_code       STRING,
    product_name       STRING,
    product_class      STRING,
    annual_fee         NUMERIC(18, 4),
    credit_limit_band  STRING,
    is_active          BOOL
);

CREATE OR REPLACE TABLE `raw_cards.cards` (
    card_id             STRING,
    customer_id         STRING,
    card_number_masked  STRING,
    product_code        STRING,
    issued_date         DATE,
    expires_date        DATE,
    status              STRING,
    credit_limit        NUMERIC(18, 4),
    linked_account_id   STRING
);

CREATE OR REPLACE TABLE `raw_cards.card_authorizations` (
    authorization_id  STRING,
    card_id           STRING,
    merchant_id       STRING,
    amount            NUMERIC(18, 4),
    currency          STRING,
    auth_status       STRING,
    decline_reason    STRING,
    auth_timestamp    TIMESTAMP,
    is_card_present   BOOL,
    ip_address        STRING
);

CREATE OR REPLACE TABLE `raw_cards.card_disputes` (
    dispute_id         STRING,
    authorization_id   STRING,
    card_id            STRING,
    dispute_reason     STRING,
    dispute_amount     NUMERIC(18, 4),
    opened_date        DATE,
    resolved_date      DATE,
    status             STRING,
    chargeback_amount  NUMERIC(18, 4)
);

CREATE OR REPLACE TABLE `raw_cards.merchants` (
    merchant_id      STRING,
    merchant_name    STRING,
    mcc_code         STRING,
    mcc_description  STRING,
    city             STRING,
    state            STRING,
    country          STRING,
    created_at       TIMESTAMP
);

-- =====================================================================
-- raw_lending
-- =====================================================================

CREATE OR REPLACE TABLE `raw_lending.loan_products` (
    product_code         STRING,
    product_name         STRING,
    product_class        STRING,
    default_term_months  INT64,
    base_apr             NUMERIC(10, 6),
    min_amount           NUMERIC(18, 4),
    max_amount           NUMERIC(18, 4),
    is_secured           BOOL,
    is_active            BOOL
);

CREATE OR REPLACE TABLE `raw_lending.loan_applications` (
    application_id       STRING,
    customer_id          STRING,
    product_code         STRING,
    applied_date         DATE,
    requested_amount     NUMERIC(18, 4),
    fico_at_application  INT64,
    annual_income        NUMERIC(18, 4),
    dti_ratio            NUMERIC(10, 6),
    purpose              STRING,
    status               STRING,
    decision_date        DATE,
    denial_reason        STRING,
    loan_officer_id      STRING,
    branch_id            STRING
);

CREATE OR REPLACE TABLE `raw_lending.loans` (
    loan_id             STRING,
    application_id      STRING,
    customer_id         STRING,
    product_code        STRING,
    principal           NUMERIC(18, 4),
    interest_rate       NUMERIC(10, 6),
    term_months         INT64,
    origination_date    DATE,
    maturity_date       DATE,
    first_payment_date  DATE,
    next_due_date       DATE,
    status              STRING,
    balance             NUMERIC(18, 4),
    monthly_payment     NUMERIC(18, 4),
    branch_id           STRING,
    days_past_due       INT64,
    ifrs9_stage         INT64,
    pd_12m              NUMERIC(10, 6),
    lgd                 NUMERIC(10, 6),
    ead                 NUMERIC(18, 4),
    ecl_amount          NUMERIC(18, 4)
);

CREATE OR REPLACE TABLE `raw_lending.loan_payments` (
    payment_id         STRING,
    loan_id            STRING,
    payment_date       DATE,
    amount             NUMERIC(18, 4),
    principal_portion  NUMERIC(18, 4),
    interest_portion   NUMERIC(18, 4),
    payment_type       STRING,
    status             STRING,
    channel            STRING,
    created_at         TIMESTAMP
);

CREATE OR REPLACE TABLE `raw_lending.collateral` (
    collateral_id    STRING,
    loan_id          STRING,
    collateral_type  STRING,
    description      STRING,
    appraised_value  NUMERIC(18, 4),
    appraisal_date   DATE,
    ltv_ratio        NUMERIC(10, 6),
    lien_position    INT64
);

-- =====================================================================
-- raw_risk
-- =====================================================================

CREATE OR REPLACE TABLE `raw_risk.credit_scores` (
    score_id     STRING,
    customer_id  STRING,
    score_type   STRING,
    score_value  INT64,
    score_date   DATE,
    bureau       STRING,
    pull_reason  STRING,
    created_at   TIMESTAMP
);

CREATE OR REPLACE TABLE `raw_risk.kyc_checks` (
    kyc_id                    STRING,
    customer_id               STRING,
    check_type                STRING,
    check_date                DATE,
    check_status              STRING,
    verification_method       STRING,
    documents_provided        STRING,
    performed_by_employee_id  STRING,
    next_review_date          DATE,
    risk_assessment_band      STRING,
    created_at                TIMESTAMP
);

CREATE OR REPLACE TABLE `raw_risk.aml_alerts` (
    alert_id                 STRING,
    customer_id              STRING,
    account_id               STRING,
    transaction_id           STRING,
    alert_type               STRING,
    severity                 STRING,
    status                   STRING,
    alert_date               DATE,
    triaged_date             DATE,
    closed_date              DATE,
    assigned_to_employee_id  STRING,
    narrative                STRING,
    scenario_code            STRING,
    created_at               TIMESTAMP
);

CREATE OR REPLACE TABLE `raw_risk.sanctions_screening` (
    screening_id        STRING,
    customer_id         STRING,
    screening_date      DATE,
    list_name           STRING,
    screen_result       STRING,
    match_score         NUMERIC(10, 6),
    matched_name        STRING,
    disposition         STRING,
    screened_by_system  STRING,
    created_at          TIMESTAMP
);

CREATE OR REPLACE TABLE `raw_risk.suspicious_activity_reports` (
    sar_id                    STRING,
    alert_id                  STRING,
    customer_id               STRING,
    filing_date               DATE,
    filing_institution        STRING,
    regulator                 STRING,
    filing_reference          STRING,
    suspicious_activity_type  STRING,
    total_amount_involved     NUMERIC(18, 4),
    narrative                 STRING,
    filed_by_employee_id      STRING,
    status                    STRING,
    created_at                TIMESTAMP
);

-- =====================================================================
-- raw_wealth
-- =====================================================================

CREATE OR REPLACE TABLE `raw_wealth.investment_accounts` (
    investment_account_id  STRING,
    customer_id            STRING,
    account_type           STRING,
    opened_date            DATE,
    status                 STRING,
    risk_tolerance         STRING,
    investment_objective   STRING,
    advisor_employee_id    STRING,
    created_at             TIMESTAMP
);

CREATE OR REPLACE TABLE `raw_wealth.securities` (
    security_id    STRING,
    ticker         STRING,
    isin           STRING,
    name           STRING,
    asset_class    STRING,
    sector         STRING,
    exchange       STRING,
    currency       STRING,
    current_price  NUMERIC(18, 4),
    price_as_of    DATE
);

CREATE OR REPLACE TABLE `raw_wealth.holdings` (
    holding_id             STRING,
    investment_account_id  STRING,
    security_id            STRING,
    quantity               NUMERIC(18, 4),
    cost_basis             NUMERIC(18, 4),
    as_of_date             DATE,
    acquired_date          DATE
);

CREATE OR REPLACE TABLE `raw_wealth.trades` (
    trade_id               STRING,
    investment_account_id  STRING,
    security_id            STRING,
    side                   STRING,
    quantity               NUMERIC(18, 4),
    trade_price            NUMERIC(18, 4),
    commission             NUMERIC(18, 4),
    trade_timestamp        TIMESTAMP,
    settle_date            DATE,
    status                 STRING,
    venue                  STRING
);

-- =====================================================================
-- raw_digital
-- =====================================================================

CREATE OR REPLACE TABLE `raw_digital.web_sessions` (
    session_id        STRING,
    customer_id       STRING,
    started_at        TIMESTAMP,
    ended_at          TIMESTAMP,
    duration_seconds  INT64,
    device_type       STRING,
    browser           STRING,
    os                STRING,
    ip_address        STRING,
    user_agent        STRING,
    referrer          STRING,
    landing_page      STRING,
    pages_viewed      INT64
);

CREATE OR REPLACE TABLE `raw_digital.mobile_app_events` (
    event_id         STRING,
    customer_id      STRING,
    event_type       STRING,
    event_timestamp  TIMESTAMP,
    device_os        STRING,
    device_model     STRING,
    app_version      STRING,
    geo_latitude     NUMERIC(10, 6),
    geo_longitude    NUMERIC(10, 6),
    session_id       STRING,
    screen_name      STRING
);

CREATE OR REPLACE TABLE `raw_digital.login_attempts` (
    login_id            STRING,
    customer_id         STRING,
    attempted_at        TIMESTAMP,
    success             BOOL,
    failure_reason      STRING,
    channel             STRING,
    ip_address          STRING,
    user_agent          STRING,
    mfa_method          STRING,
    device_fingerprint  STRING
);

-- =====================================================================
-- raw_marketing
-- =====================================================================

CREATE OR REPLACE TABLE `raw_marketing.campaigns` (
    campaign_id        STRING,
    campaign_name      STRING,
    channel            STRING,
    objective          STRING,
    start_date         DATE,
    end_date           DATE,
    budget             NUMERIC(18, 4),
    target_segment     STRING,
    owner_employee_id  STRING,
    status             STRING
);

CREATE OR REPLACE TABLE `raw_marketing.customer_segments` (
    segment_code  STRING,
    segment_name  STRING,
    description   STRING
);

CREATE OR REPLACE TABLE `raw_marketing.customer_interactions` (
    interaction_id         STRING,
    customer_id            STRING,
    campaign_id            STRING,
    channel                STRING,
    topic                  STRING,
    employee_id            STRING,
    interaction_timestamp  TIMESTAMP,
    duration_minutes       INT64,
    outcome                STRING,
    satisfaction_score     INT64,
    notes                  STRING
);
