-- =====================================================================
-- Redshift initialization for the Banking demo
-- =====================================================================
-- GENERATED by scripts/generate_ddl.py from schema/registry.py — do not edit.
--
-- Creates the raw schemas and source tables that mirror the CSV seeds in
-- dbt/seeds/raw_*/. Columns match the CSV headers in order, so the COPY
-- commands generated by scripts/redshift/load_to_redshift.sh can load
-- straight from S3 without column lists.
--
-- Encoding favours ZSTD for VARCHAR/NUMERIC/DATE/TIMESTAMP and AZ64 for
-- INTEGER. Distribution defaults to AUTO; small lookups use ALL and
-- high-volume fact tables use KEY distribution with a SORTKEY on the
-- natural time column.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Schemas
-- ---------------------------------------------------------------------
DROP SCHEMA IF EXISTS raw_core_banking CASCADE;
CREATE SCHEMA raw_core_banking;

DROP SCHEMA IF EXISTS raw_transactions CASCADE;
CREATE SCHEMA raw_transactions;

DROP SCHEMA IF EXISTS raw_cards CASCADE;
CREATE SCHEMA raw_cards;

DROP SCHEMA IF EXISTS raw_lending CASCADE;
CREATE SCHEMA raw_lending;

DROP SCHEMA IF EXISTS raw_risk CASCADE;
CREATE SCHEMA raw_risk;

DROP SCHEMA IF EXISTS raw_wealth CASCADE;
CREATE SCHEMA raw_wealth;

DROP SCHEMA IF EXISTS raw_digital CASCADE;
CREATE SCHEMA raw_digital;

DROP SCHEMA IF EXISTS raw_marketing CASCADE;
CREATE SCHEMA raw_marketing;


-- =====================================================================
-- raw_core_banking
-- =====================================================================

-- customers
CREATE TABLE raw_core_banking.customers (
    customer_id          VARCHAR(30)   ENCODE ZSTD,
    first_name           VARCHAR(120)  ENCODE ZSTD,
    last_name            VARCHAR(80)   ENCODE ZSTD,
    email                VARCHAR(160)  ENCODE ZSTD,
    phone                VARCHAR(20)   ENCODE ZSTD,
    ssn                  VARCHAR(11)   ENCODE ZSTD,
    tax_id               VARCHAR(20)   ENCODE ZSTD,
    date_of_birth        DATE          ENCODE ZSTD,
    customer_segment     VARCHAR(30)   ENCODE ZSTD,
    customer_type        VARCHAR(30)   ENCODE ZSTD,
    branch_id            VARCHAR(30)   ENCODE ZSTD,
    primary_employee_id  VARCHAR(30)   ENCODE ZSTD,
    kyc_status           VARCHAR(20)   ENCODE ZSTD,
    risk_band            VARCHAR(20)   ENCODE ZSTD,
    created_at           TIMESTAMP     ENCODE ZSTD,
    updated_at           TIMESTAMP     ENCODE ZSTD
)
DISTSTYLE AUTO;

-- customer_addresses
CREATE TABLE raw_core_banking.customer_addresses (
    address_id      VARCHAR(30)   ENCODE ZSTD,
    customer_id     VARCHAR(30)   ENCODE ZSTD,
    address_type    VARCHAR(20)   ENCODE ZSTD,
    address_line_1  VARCHAR(120)  ENCODE ZSTD,
    address_line_2  VARCHAR(120)  ENCODE ZSTD,
    city            VARCHAR(80)   ENCODE ZSTD,
    state           VARCHAR(20)   ENCODE ZSTD,
    postal_code     VARCHAR(20)   ENCODE ZSTD,
    country         VARCHAR(20)   ENCODE ZSTD,
    is_primary      BOOLEAN       ENCODE RAW,
    effective_from  DATE          ENCODE ZSTD,
    effective_to    DATE          ENCODE ZSTD
)
DISTSTYLE AUTO;

-- customer_contacts
CREATE TABLE raw_core_banking.customer_contacts (
    contact_id     VARCHAR(30)   ENCODE ZSTD,
    customer_id    VARCHAR(30)   ENCODE ZSTD,
    contact_type   VARCHAR(20)   ENCODE ZSTD,
    contact_value  VARCHAR(120)  ENCODE ZSTD,
    is_primary     BOOLEAN       ENCODE RAW,
    is_verified    BOOLEAN       ENCODE RAW,
    opt_out        BOOLEAN       ENCODE RAW,
    added_at       TIMESTAMP     ENCODE ZSTD
)
DISTSTYLE AUTO;

-- branches
CREATE TABLE raw_core_banking.branches (
    branch_id            VARCHAR(30)   ENCODE ZSTD,
    branch_name          VARCHAR(80)   ENCODE ZSTD,
    address_line_1       VARCHAR(120)  ENCODE ZSTD,
    city                 VARCHAR(80)   ENCODE ZSTD,
    state                VARCHAR(20)   ENCODE ZSTD,
    postal_code          VARCHAR(20)   ENCODE ZSTD,
    country              VARCHAR(20)   ENCODE ZSTD,
    region               VARCHAR(30)   ENCODE ZSTD,
    phone                VARCHAR(20)   ENCODE ZSTD,
    manager_employee_id  VARCHAR(30)   ENCODE ZSTD,
    opened_date          DATE          ENCODE ZSTD,
    closed_date          DATE          ENCODE ZSTD,
    is_active            BOOLEAN       ENCODE RAW
)
DISTSTYLE ALL;

-- employees
CREATE TABLE raw_core_banking.employees (
    employee_id       VARCHAR(30)   ENCODE ZSTD,
    first_name        VARCHAR(80)   ENCODE ZSTD,
    last_name         VARCHAR(80)   ENCODE ZSTD,
    email             VARCHAR(120)  ENCODE ZSTD,
    phone             VARCHAR(20)   ENCODE ZSTD,
    hire_date         DATE          ENCODE ZSTD,
    termination_date  DATE          ENCODE ZSTD,
    role              VARCHAR(80)   ENCODE ZSTD,
    branch_id         VARCHAR(30)   ENCODE ZSTD,
    manager_id        VARCHAR(30)   ENCODE ZSTD,
    salary_band       VARCHAR(20)   ENCODE ZSTD,
    is_active         BOOLEAN       ENCODE RAW
)
DISTSTYLE AUTO;

-- accounts
CREATE TABLE raw_core_banking.accounts (
    account_id     VARCHAR(30)    ENCODE ZSTD,
    customer_id    VARCHAR(30)    ENCODE ZSTD,
    account_type   VARCHAR(30)    ENCODE ZSTD,
    product_code   VARCHAR(30)    ENCODE ZSTD,
    opened_date    DATE           ENCODE ZSTD,
    closed_date    DATE           ENCODE ZSTD,
    status         VARCHAR(20)    ENCODE ZSTD,
    balance        NUMERIC(18,4)  ENCODE ZSTD,
    currency       VARCHAR(3)     ENCODE ZSTD,
    branch_id      VARCHAR(30)    ENCODE ZSTD,
    interest_rate  NUMERIC(10,6)  ENCODE ZSTD,
    credit_limit   NUMERIC(18,4)  ENCODE ZSTD,
    is_joint       BOOLEAN        ENCODE RAW,
    created_at     TIMESTAMP      ENCODE ZSTD,
    updated_at     TIMESTAMP      ENCODE ZSTD
)
DISTSTYLE AUTO;

-- account_holders
CREATE TABLE raw_core_banking.account_holders (
    holder_id     VARCHAR(30)  ENCODE ZSTD,
    account_id    VARCHAR(30)  ENCODE ZSTD,
    customer_id   VARCHAR(30)  ENCODE ZSTD,
    holder_order  INTEGER      ENCODE AZ64,
    relationship  VARCHAR(30)  ENCODE ZSTD,
    added_at      TIMESTAMP    ENCODE ZSTD,
    removed_at    TIMESTAMP    ENCODE ZSTD
)
DISTSTYLE AUTO;

-- account_types
CREATE TABLE raw_core_banking.account_types (
    account_type_code  VARCHAR(30)  ENCODE ZSTD,
    account_type_name  VARCHAR(80)  ENCODE ZSTD,
    product_category   VARCHAR(30)  ENCODE ZSTD
)
DISTSTYLE ALL;


-- =====================================================================
-- raw_transactions
-- =====================================================================

-- transactions
CREATE TABLE raw_transactions.transactions (
    transaction_id    VARCHAR(30)    ENCODE ZSTD,
    account_id        VARCHAR(30)    ENCODE ZSTD,
    posted_at         TIMESTAMP      ENCODE ZSTD,
    amount            NUMERIC(18,4)  ENCODE ZSTD,
    currency          VARCHAR(3)     ENCODE ZSTD,
    transaction_type  VARCHAR(30)    ENCODE ZSTD,
    merchant_id       VARCHAR(30)    ENCODE ZSTD,
    description       VARCHAR(500)   ENCODE ZSTD,
    is_reversal       BOOLEAN        ENCODE RAW,
    channel           VARCHAR(30)    ENCODE ZSTD,
    running_balance   NUMERIC(18,4)  ENCODE ZSTD,
    created_at        TIMESTAMP      ENCODE ZSTD
)
DISTSTYLE KEY DISTKEY (account_id) SORTKEY (posted_at);

-- transaction_categories
CREATE TABLE raw_transactions.transaction_categories (
    category_code   VARCHAR(30)  ENCODE ZSTD,
    category_name   VARCHAR(80)  ENCODE ZSTD,
    category_group  VARCHAR(30)  ENCODE ZSTD,
    sign_hint       VARCHAR(20)  ENCODE ZSTD
)
DISTSTYLE ALL;

-- atm_withdrawals
CREATE TABLE raw_transactions.atm_withdrawals (
    atm_withdrawal_id      VARCHAR(30)    ENCODE ZSTD,
    account_id             VARCHAR(30)    ENCODE ZSTD,
    atm_terminal_id        VARCHAR(30)    ENCODE ZSTD,
    atm_city               VARCHAR(80)    ENCODE ZSTD,
    atm_state              VARCHAR(20)    ENCODE ZSTD,
    amount                 NUMERIC(18,4)  ENCODE ZSTD,
    fee_amount             NUMERIC(18,4)  ENCODE ZSTD,
    withdrawn_at           TIMESTAMP      ENCODE ZSTD,
    is_foreign             BOOLEAN        ENCODE RAW,
    network                VARCHAR(20)    ENCODE ZSTD,
    parent_transaction_id  VARCHAR(30)    ENCODE ZSTD
)
DISTSTYLE KEY DISTKEY (account_id) SORTKEY (withdrawn_at);

-- wire_transfers
CREATE TABLE raw_transactions.wire_transfers (
    wire_id                VARCHAR(30)    ENCODE ZSTD,
    account_id             VARCHAR(30)    ENCODE ZSTD,
    direction              VARCHAR(20)    ENCODE ZSTD,
    amount                 NUMERIC(18,4)  ENCODE ZSTD,
    currency               VARCHAR(3)     ENCODE ZSTD,
    from_iban              VARCHAR(40)    ENCODE ZSTD,
    to_iban                VARCHAR(40)    ENCODE ZSTD,
    swift_code             VARCHAR(20)    ENCODE ZSTD,
    fee_amount             NUMERIC(18,4)  ENCODE ZSTD,
    originator_name        VARCHAR(120)   ENCODE ZSTD,
    beneficiary_name       VARCHAR(120)   ENCODE ZSTD,
    wire_purpose           VARCHAR(120)   ENCODE ZSTD,
    sent_at                TIMESTAMP      ENCODE ZSTD,
    status                 VARCHAR(20)    ENCODE ZSTD,
    parent_transaction_id  VARCHAR(30)    ENCODE ZSTD
)
DISTSTYLE KEY DISTKEY (account_id) SORTKEY (sent_at);

-- ach_transfers
CREATE TABLE raw_transactions.ach_transfers (
    ach_id                       VARCHAR(30)    ENCODE ZSTD,
    account_id                   VARCHAR(30)    ENCODE ZSTD,
    direction                    VARCHAR(20)    ENCODE ZSTD,
    amount                       NUMERIC(18,4)  ENCODE ZSTD,
    ach_type                     VARCHAR(20)    ENCODE ZSTD,
    counterparty_routing         VARCHAR(20)    ENCODE ZSTD,
    counterparty_account_masked  VARCHAR(40)    ENCODE ZSTD,
    counterparty_name            VARCHAR(120)   ENCODE ZSTD,
    settled_date                 DATE           ENCODE ZSTD,
    originated_at                TIMESTAMP      ENCODE ZSTD,
    status                       VARCHAR(20)    ENCODE ZSTD,
    sec_code                     VARCHAR(20)    ENCODE ZSTD,
    return_reason_code           VARCHAR(10)    ENCODE ZSTD,
    parent_transaction_id        VARCHAR(30)    ENCODE ZSTD
)
DISTSTYLE KEY DISTKEY (account_id) SORTKEY (originated_at);


-- =====================================================================
-- raw_cards
-- =====================================================================

-- card_products
CREATE TABLE raw_cards.card_products (
    product_code       VARCHAR(30)    ENCODE ZSTD,
    product_name       VARCHAR(80)    ENCODE ZSTD,
    product_class      VARCHAR(30)    ENCODE ZSTD,
    annual_fee         NUMERIC(18,4)  ENCODE ZSTD,
    credit_limit_band  VARCHAR(20)    ENCODE ZSTD,
    is_active          BOOLEAN        ENCODE RAW
)
DISTSTYLE ALL;

-- cards
CREATE TABLE raw_cards.cards (
    card_id             VARCHAR(30)    ENCODE ZSTD,
    customer_id         VARCHAR(30)    ENCODE ZSTD,
    card_number_masked  VARCHAR(30)    ENCODE ZSTD,
    product_code        VARCHAR(30)    ENCODE ZSTD,
    issued_date         DATE           ENCODE ZSTD,
    expires_date        DATE           ENCODE ZSTD,
    status              VARCHAR(20)    ENCODE ZSTD,
    credit_limit        NUMERIC(18,4)  ENCODE ZSTD,
    linked_account_id   VARCHAR(30)    ENCODE ZSTD
)
DISTSTYLE AUTO;

-- card_authorizations
CREATE TABLE raw_cards.card_authorizations (
    authorization_id  VARCHAR(30)    ENCODE ZSTD,
    card_id           VARCHAR(30)    ENCODE ZSTD,
    merchant_id       VARCHAR(30)    ENCODE ZSTD,
    amount            NUMERIC(18,4)  ENCODE ZSTD,
    currency          VARCHAR(3)     ENCODE ZSTD,
    auth_status       VARCHAR(20)    ENCODE ZSTD,
    decline_reason    VARCHAR(120)   ENCODE ZSTD,
    auth_timestamp    TIMESTAMP      ENCODE ZSTD,
    is_card_present   BOOLEAN        ENCODE RAW,
    ip_address        VARCHAR(45)    ENCODE ZSTD
)
DISTSTYLE KEY DISTKEY (card_id) SORTKEY (auth_timestamp);

-- card_disputes
CREATE TABLE raw_cards.card_disputes (
    dispute_id         VARCHAR(30)    ENCODE ZSTD,
    authorization_id   VARCHAR(30)    ENCODE ZSTD,
    card_id            VARCHAR(30)    ENCODE ZSTD,
    dispute_reason     VARCHAR(120)   ENCODE ZSTD,
    dispute_amount     NUMERIC(18,4)  ENCODE ZSTD,
    opened_date        DATE           ENCODE ZSTD,
    resolved_date      DATE           ENCODE ZSTD,
    status             VARCHAR(40)    ENCODE ZSTD,
    chargeback_amount  NUMERIC(18,4)  ENCODE ZSTD
)
DISTSTYLE AUTO;

-- merchants
CREATE TABLE raw_cards.merchants (
    merchant_id      VARCHAR(30)   ENCODE ZSTD,
    merchant_name    VARCHAR(120)  ENCODE ZSTD,
    mcc_code         VARCHAR(20)   ENCODE ZSTD,
    mcc_description  VARCHAR(120)  ENCODE ZSTD,
    city             VARCHAR(80)   ENCODE ZSTD,
    state            VARCHAR(20)   ENCODE ZSTD,
    country          VARCHAR(20)   ENCODE ZSTD,
    created_at       TIMESTAMP     ENCODE ZSTD
)
DISTSTYLE AUTO;


-- =====================================================================
-- raw_lending
-- =====================================================================

-- loan_products
CREATE TABLE raw_lending.loan_products (
    product_code         VARCHAR(30)    ENCODE ZSTD,
    product_name         VARCHAR(80)    ENCODE ZSTD,
    product_class        VARCHAR(30)    ENCODE ZSTD,
    default_term_months  INTEGER        ENCODE AZ64,
    base_apr             NUMERIC(10,6)  ENCODE ZSTD,
    min_amount           NUMERIC(18,4)  ENCODE ZSTD,
    max_amount           NUMERIC(18,4)  ENCODE ZSTD,
    is_secured           BOOLEAN        ENCODE RAW,
    is_active            BOOLEAN        ENCODE RAW
)
DISTSTYLE ALL;

-- loan_applications
CREATE TABLE raw_lending.loan_applications (
    application_id       VARCHAR(30)    ENCODE ZSTD,
    customer_id          VARCHAR(30)    ENCODE ZSTD,
    product_code         VARCHAR(30)    ENCODE ZSTD,
    applied_date         DATE           ENCODE ZSTD,
    requested_amount     NUMERIC(18,4)  ENCODE ZSTD,
    fico_at_application  INTEGER        ENCODE AZ64,
    annual_income        NUMERIC(18,4)  ENCODE ZSTD,
    dti_ratio            NUMERIC(10,6)  ENCODE ZSTD,
    purpose              VARCHAR(120)   ENCODE ZSTD,
    status               VARCHAR(20)    ENCODE ZSTD,
    decision_date        DATE           ENCODE ZSTD,
    denial_reason        VARCHAR(120)   ENCODE ZSTD,
    loan_officer_id      VARCHAR(30)    ENCODE ZSTD,
    branch_id            VARCHAR(30)    ENCODE ZSTD
)
DISTSTYLE AUTO;

-- loans
CREATE TABLE raw_lending.loans (
    loan_id             VARCHAR(30)    ENCODE ZSTD,
    application_id      VARCHAR(30)    ENCODE ZSTD,
    customer_id         VARCHAR(30)    ENCODE ZSTD,
    product_code        VARCHAR(30)    ENCODE ZSTD,
    principal           NUMERIC(18,4)  ENCODE ZSTD,
    interest_rate       NUMERIC(10,6)  ENCODE ZSTD,
    term_months         INTEGER        ENCODE AZ64,
    origination_date    DATE           ENCODE ZSTD,
    maturity_date       DATE           ENCODE ZSTD,
    first_payment_date  DATE           ENCODE ZSTD,
    next_due_date       DATE           ENCODE ZSTD,
    status              VARCHAR(20)    ENCODE ZSTD,
    balance             NUMERIC(18,4)  ENCODE ZSTD,
    monthly_payment     NUMERIC(18,4)  ENCODE ZSTD,
    branch_id           VARCHAR(30)    ENCODE ZSTD,
    days_past_due       INTEGER        ENCODE AZ64,
    ifrs9_stage         INTEGER        ENCODE AZ64,
    pd_12m              NUMERIC(10,6)  ENCODE ZSTD,
    lgd                 NUMERIC(10,6)  ENCODE ZSTD,
    ead                 NUMERIC(18,4)  ENCODE ZSTD,
    ecl_amount          NUMERIC(18,4)  ENCODE ZSTD
)
DISTSTYLE AUTO;

-- loan_payments
CREATE TABLE raw_lending.loan_payments (
    payment_id         VARCHAR(30)    ENCODE ZSTD,
    loan_id            VARCHAR(30)    ENCODE ZSTD,
    payment_date       DATE           ENCODE ZSTD,
    amount             NUMERIC(18,4)  ENCODE ZSTD,
    principal_portion  NUMERIC(18,4)  ENCODE ZSTD,
    interest_portion   NUMERIC(18,4)  ENCODE ZSTD,
    payment_type       VARCHAR(30)    ENCODE ZSTD,
    status             VARCHAR(20)    ENCODE ZSTD,
    channel            VARCHAR(30)    ENCODE ZSTD,
    created_at         TIMESTAMP      ENCODE ZSTD
)
DISTSTYLE KEY DISTKEY (loan_id) SORTKEY (payment_date);

-- collateral
CREATE TABLE raw_lending.collateral (
    collateral_id    VARCHAR(30)    ENCODE ZSTD,
    loan_id          VARCHAR(30)    ENCODE ZSTD,
    collateral_type  VARCHAR(30)    ENCODE ZSTD,
    description      VARCHAR(500)   ENCODE ZSTD,
    appraised_value  NUMERIC(18,4)  ENCODE ZSTD,
    appraisal_date   DATE           ENCODE ZSTD,
    ltv_ratio        NUMERIC(10,6)  ENCODE ZSTD,
    lien_position    INTEGER        ENCODE AZ64
)
DISTSTYLE AUTO;


-- =====================================================================
-- raw_risk
-- =====================================================================

-- credit_scores
CREATE TABLE raw_risk.credit_scores (
    score_id     VARCHAR(30)  ENCODE ZSTD,
    customer_id  VARCHAR(30)  ENCODE ZSTD,
    score_type   VARCHAR(30)  ENCODE ZSTD,
    score_value  INTEGER      ENCODE AZ64,
    score_date   DATE         ENCODE ZSTD,
    bureau       VARCHAR(30)  ENCODE ZSTD,
    pull_reason  VARCHAR(80)  ENCODE ZSTD,
    created_at   TIMESTAMP    ENCODE ZSTD
)
DISTSTYLE AUTO;

-- kyc_checks
CREATE TABLE raw_risk.kyc_checks (
    kyc_id                    VARCHAR(30)   ENCODE ZSTD,
    customer_id               VARCHAR(30)   ENCODE ZSTD,
    check_type                VARCHAR(30)   ENCODE ZSTD,
    check_date                DATE          ENCODE ZSTD,
    check_status              VARCHAR(20)   ENCODE ZSTD,
    verification_method       VARCHAR(80)   ENCODE ZSTD,
    documents_provided        VARCHAR(500)  ENCODE ZSTD,
    performed_by_employee_id  VARCHAR(30)   ENCODE ZSTD,
    next_review_date          DATE          ENCODE ZSTD,
    risk_assessment_band      VARCHAR(20)   ENCODE ZSTD,
    created_at                TIMESTAMP     ENCODE ZSTD
)
DISTSTYLE AUTO;

-- aml_alerts
CREATE TABLE raw_risk.aml_alerts (
    alert_id                 VARCHAR(30)   ENCODE ZSTD,
    customer_id              VARCHAR(30)   ENCODE ZSTD,
    account_id               VARCHAR(30)   ENCODE ZSTD,
    transaction_id           VARCHAR(30)   ENCODE ZSTD,
    alert_type               VARCHAR(30)   ENCODE ZSTD,
    severity                 VARCHAR(20)   ENCODE ZSTD,
    status                   VARCHAR(20)   ENCODE ZSTD,
    alert_date               DATE          ENCODE ZSTD,
    triaged_date             DATE          ENCODE ZSTD,
    closed_date              DATE          ENCODE ZSTD,
    assigned_to_employee_id  VARCHAR(30)   ENCODE ZSTD,
    narrative                VARCHAR(500)  ENCODE ZSTD,
    scenario_code            VARCHAR(30)   ENCODE ZSTD,
    created_at               TIMESTAMP     ENCODE ZSTD
)
DISTSTYLE AUTO;

-- sanctions_screening
CREATE TABLE raw_risk.sanctions_screening (
    screening_id        VARCHAR(30)    ENCODE ZSTD,
    customer_id         VARCHAR(30)    ENCODE ZSTD,
    screening_date      DATE           ENCODE ZSTD,
    list_name           VARCHAR(80)    ENCODE ZSTD,
    screen_result       VARCHAR(20)    ENCODE ZSTD,
    match_score         NUMERIC(10,6)  ENCODE ZSTD,
    matched_name        VARCHAR(120)   ENCODE ZSTD,
    disposition         VARCHAR(80)    ENCODE ZSTD,
    screened_by_system  VARCHAR(80)    ENCODE ZSTD,
    created_at          TIMESTAMP      ENCODE ZSTD
)
DISTSTYLE AUTO;

-- suspicious_activity_reports
CREATE TABLE raw_risk.suspicious_activity_reports (
    sar_id                    VARCHAR(30)    ENCODE ZSTD,
    alert_id                  VARCHAR(30)    ENCODE ZSTD,
    customer_id               VARCHAR(30)    ENCODE ZSTD,
    filing_date               DATE           ENCODE ZSTD,
    filing_institution        VARCHAR(120)   ENCODE ZSTD,
    regulator                 VARCHAR(80)    ENCODE ZSTD,
    filing_reference          VARCHAR(80)    ENCODE ZSTD,
    suspicious_activity_type  VARCHAR(80)    ENCODE ZSTD,
    total_amount_involved     NUMERIC(18,4)  ENCODE ZSTD,
    narrative                 VARCHAR(500)   ENCODE ZSTD,
    filed_by_employee_id      VARCHAR(30)    ENCODE ZSTD,
    status                    VARCHAR(20)    ENCODE ZSTD,
    created_at                TIMESTAMP      ENCODE ZSTD
)
DISTSTYLE AUTO;


-- =====================================================================
-- raw_wealth
-- =====================================================================

-- investment_accounts
CREATE TABLE raw_wealth.investment_accounts (
    investment_account_id  VARCHAR(30)  ENCODE ZSTD,
    customer_id            VARCHAR(30)  ENCODE ZSTD,
    account_type           VARCHAR(30)  ENCODE ZSTD,
    opened_date            DATE         ENCODE ZSTD,
    status                 VARCHAR(20)  ENCODE ZSTD,
    risk_tolerance         VARCHAR(20)  ENCODE ZSTD,
    investment_objective   VARCHAR(80)  ENCODE ZSTD,
    advisor_employee_id    VARCHAR(30)  ENCODE ZSTD,
    created_at             TIMESTAMP    ENCODE ZSTD
)
DISTSTYLE AUTO;

-- securities
CREATE TABLE raw_wealth.securities (
    security_id    VARCHAR(30)    ENCODE ZSTD,
    ticker         VARCHAR(20)    ENCODE ZSTD,
    isin           VARCHAR(20)    ENCODE ZSTD,
    name           VARCHAR(120)   ENCODE ZSTD,
    asset_class    VARCHAR(30)    ENCODE ZSTD,
    sector         VARCHAR(80)    ENCODE ZSTD,
    exchange       VARCHAR(20)    ENCODE ZSTD,
    currency       VARCHAR(3)     ENCODE ZSTD,
    current_price  NUMERIC(18,4)  ENCODE ZSTD,
    price_as_of    DATE           ENCODE ZSTD
)
DISTSTYLE ALL;

-- holdings
CREATE TABLE raw_wealth.holdings (
    holding_id             VARCHAR(30)    ENCODE ZSTD,
    investment_account_id  VARCHAR(30)    ENCODE ZSTD,
    security_id            VARCHAR(30)    ENCODE ZSTD,
    quantity               NUMERIC(18,4)  ENCODE ZSTD,
    cost_basis             NUMERIC(18,4)  ENCODE ZSTD,
    as_of_date             DATE           ENCODE ZSTD,
    acquired_date          DATE           ENCODE ZSTD
)
DISTSTYLE KEY DISTKEY (investment_account_id);

-- trades
CREATE TABLE raw_wealth.trades (
    trade_id               VARCHAR(30)    ENCODE ZSTD,
    investment_account_id  VARCHAR(30)    ENCODE ZSTD,
    security_id            VARCHAR(30)    ENCODE ZSTD,
    side                   VARCHAR(20)    ENCODE ZSTD,
    quantity               NUMERIC(18,4)  ENCODE ZSTD,
    trade_price            NUMERIC(18,4)  ENCODE ZSTD,
    commission             NUMERIC(18,4)  ENCODE ZSTD,
    trade_timestamp        TIMESTAMP      ENCODE ZSTD,
    settle_date            DATE           ENCODE ZSTD,
    status                 VARCHAR(20)    ENCODE ZSTD,
    venue                  VARCHAR(30)    ENCODE ZSTD
)
DISTSTYLE KEY DISTKEY (investment_account_id) SORTKEY (trade_timestamp);


-- =====================================================================
-- raw_digital
-- =====================================================================

-- web_sessions
CREATE TABLE raw_digital.web_sessions (
    session_id        VARCHAR(30)   ENCODE ZSTD,
    customer_id       VARCHAR(30)   ENCODE ZSTD,
    started_at        TIMESTAMP     ENCODE ZSTD,
    ended_at          TIMESTAMP     ENCODE ZSTD,
    duration_seconds  INTEGER       ENCODE AZ64,
    device_type       VARCHAR(30)   ENCODE ZSTD,
    browser           VARCHAR(30)   ENCODE ZSTD,
    os                VARCHAR(30)   ENCODE ZSTD,
    ip_address        VARCHAR(45)   ENCODE ZSTD,
    user_agent        VARCHAR(500)  ENCODE ZSTD,
    referrer          VARCHAR(500)  ENCODE ZSTD,
    landing_page      VARCHAR(500)  ENCODE ZSTD,
    pages_viewed      INTEGER       ENCODE AZ64
)
DISTSTYLE KEY DISTKEY (customer_id) SORTKEY (started_at);

-- mobile_app_events
CREATE TABLE raw_digital.mobile_app_events (
    event_id         VARCHAR(30)    ENCODE ZSTD,
    customer_id      VARCHAR(30)    ENCODE ZSTD,
    event_type       VARCHAR(30)    ENCODE ZSTD,
    event_timestamp  TIMESTAMP      ENCODE ZSTD,
    device_os        VARCHAR(30)    ENCODE ZSTD,
    device_model     VARCHAR(80)    ENCODE ZSTD,
    app_version      VARCHAR(20)    ENCODE ZSTD,
    geo_latitude     NUMERIC(10,6)  ENCODE ZSTD,
    geo_longitude    NUMERIC(10,6)  ENCODE ZSTD,
    session_id       VARCHAR(30)    ENCODE ZSTD,
    screen_name      VARCHAR(80)    ENCODE ZSTD
)
DISTSTYLE KEY DISTKEY (customer_id) SORTKEY (event_timestamp);

-- login_attempts
CREATE TABLE raw_digital.login_attempts (
    login_id            VARCHAR(30)   ENCODE ZSTD,
    customer_id         VARCHAR(30)   ENCODE ZSTD,
    attempted_at        TIMESTAMP     ENCODE ZSTD,
    success             BOOLEAN       ENCODE RAW,
    failure_reason      VARCHAR(120)  ENCODE ZSTD,
    channel             VARCHAR(30)   ENCODE ZSTD,
    ip_address          VARCHAR(45)   ENCODE ZSTD,
    user_agent          VARCHAR(500)  ENCODE ZSTD,
    mfa_method          VARCHAR(30)   ENCODE ZSTD,
    device_fingerprint  VARCHAR(120)  ENCODE ZSTD
)
DISTSTYLE KEY DISTKEY (customer_id) SORTKEY (attempted_at);


-- =====================================================================
-- raw_marketing
-- =====================================================================

-- campaigns
CREATE TABLE raw_marketing.campaigns (
    campaign_id        VARCHAR(30)    ENCODE ZSTD,
    campaign_name      VARCHAR(120)   ENCODE ZSTD,
    channel            VARCHAR(30)    ENCODE ZSTD,
    objective          VARCHAR(120)   ENCODE ZSTD,
    start_date         DATE           ENCODE ZSTD,
    end_date           DATE           ENCODE ZSTD,
    budget             NUMERIC(18,4)  ENCODE ZSTD,
    target_segment     VARCHAR(30)    ENCODE ZSTD,
    owner_employee_id  VARCHAR(30)    ENCODE ZSTD,
    status             VARCHAR(20)    ENCODE ZSTD
)
DISTSTYLE AUTO;

-- customer_segments
CREATE TABLE raw_marketing.customer_segments (
    segment_code  VARCHAR(30)   ENCODE ZSTD,
    segment_name  VARCHAR(80)   ENCODE ZSTD,
    description   VARCHAR(500)  ENCODE ZSTD
)
DISTSTYLE ALL;

-- customer_interactions
CREATE TABLE raw_marketing.customer_interactions (
    interaction_id         VARCHAR(30)   ENCODE ZSTD,
    customer_id            VARCHAR(30)   ENCODE ZSTD,
    campaign_id            VARCHAR(30)   ENCODE ZSTD,
    channel                VARCHAR(30)   ENCODE ZSTD,
    topic                  VARCHAR(120)  ENCODE ZSTD,
    employee_id            VARCHAR(30)   ENCODE ZSTD,
    interaction_timestamp  TIMESTAMP     ENCODE ZSTD,
    duration_minutes       INTEGER       ENCODE AZ64,
    outcome                VARCHAR(80)   ENCODE ZSTD,
    satisfaction_score     INTEGER       ENCODE AZ64,
    notes                  VARCHAR(500)  ENCODE ZSTD
)
DISTSTYLE KEY DISTKEY (customer_id) SORTKEY (interaction_timestamp);
