#!/usr/bin/env bash
# =====================================================================
# load_to_redshift.sh
# ---------------------------------------------------------------------
# Loads every (schema, table) pair from S3 into the matching Redshift
# table using COPY ... FROM ... IAM_ROLE. Run after:
#
#   1. scripts/bootstrap_redshift.sh   (creates tables)
#   2. scripts/upload_to_s3.sh         (publishes CSVs to S3)
#
# Required env:
#   REDSHIFT_HOST        Redshift cluster endpoint
#   REDSHIFT_PORT        Cluster port (typically 5439)
#   REDSHIFT_DATABASE    Database name
#   REDSHIFT_USER        Username
#   REDSHIFT_PASSWORD    Password
#   REDSHIFT_IAM_ROLE    IAM role ARN attached to the cluster with S3 read access
#   BANKING_S3_BUCKET    Source S3 bucket name
#
# Optional env:
#   BANKING_S3_PREFIX    S3 key prefix (default: raw)
#   BANKING_S3_REGION    Bucket region. Required when bucket and Redshift are
#                        in different AWS regions (e.g. bucket eu-west-1,
#                        Redshift us-east-2). Emits `REGION '<value>'` on each
#                        COPY. Leave unset when both are in the same region.
# =====================================================================
set -euo pipefail

: "${REDSHIFT_HOST:?Set REDSHIFT_HOST to the Redshift cluster endpoint}"
: "${REDSHIFT_PORT:?Set REDSHIFT_PORT to the Redshift port (e.g. 5439)}"
: "${REDSHIFT_DATABASE:?Set REDSHIFT_DATABASE to the target database}"
: "${REDSHIFT_USER:?Set REDSHIFT_USER to the Redshift user}"
: "${REDSHIFT_PASSWORD:?Set REDSHIFT_PASSWORD to the Redshift password}"
: "${REDSHIFT_IAM_ROLE:?Set REDSHIFT_IAM_ROLE to the IAM role ARN for COPY}"
: "${BANKING_S3_BUCKET:?Set BANKING_S3_BUCKET to the source S3 bucket}"
BANKING_S3_PREFIX="${BANKING_S3_PREFIX:-raw}"
BANKING_S3_REGION="${BANKING_S3_REGION:-}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SEEDS_DIR="${PROJECT_ROOT}/dbt/seeds"

if [[ ! -d "${SEEDS_DIR}" ]]; then
    echo "Seeds directory not found: ${SEEDS_DIR}" >&2
    exit 1
fi

echo "Banking demo: loading data into Redshift via COPY from S3"
echo "  Host:     ${REDSHIFT_HOST}:${REDSHIFT_PORT}"
echo "  Database: ${REDSHIFT_DATABASE}"
echo "  Bucket:   s3://${BANKING_S3_BUCKET}/${BANKING_S3_PREFIX}"
echo "  IAM role: ${REDSHIFT_IAM_ROLE}"
if [[ -n "${BANKING_S3_REGION}" ]]; then
    echo "  Region:   ${BANKING_S3_REGION}  (cross-region COPY)"
fi
echo

# ---------------------------------------------------------------------
# Build a temporary SQL file with one COPY statement per table.
# ---------------------------------------------------------------------
TMP_SQL="$(mktemp -t banking_copy.XXXXXX.sql)"
trap 'rm -f "${TMP_SQL}"' EXIT

{
    echo "-- Auto-generated by scripts/load_to_redshift.sh"
    echo "BEGIN;"
    echo
} > "${TMP_SQL}"

shopt -s nullglob
table_count=0

for schema_dir in "${SEEDS_DIR}"/raw_*/; do
    schema="$(basename "${schema_dir%/}")"
    for csv in "${schema_dir}"*.csv; do
        table="$(basename "${csv}" .csv)"
        s3_uri="s3://${BANKING_S3_BUCKET}/${BANKING_S3_PREFIX}/${schema}/${table}/${table}.csv"

        {
            echo "-- ${schema}.${table}"
            # TRUNCATE so re-running is idempotent (avoids row duplication).
            echo "TRUNCATE TABLE ${schema}.${table};"
            echo "COPY ${schema}.${table}"
            echo "FROM '${s3_uri}'"
            echo "IAM_ROLE '${REDSHIFT_IAM_ROLE}'"
            echo "FORMAT CSV"
            echo "IGNOREHEADER 1"
            echo "TIMEFORMAT 'auto'"
            echo "DATEFORMAT 'auto'"
            echo "MAXERROR 5"
            # generate_seed_data.py writes \N for missing values so that
            # Redshift and BigQuery derive identical NULLs from one CSV set.
            # EMPTYASNULL/BLANKSASNULL are deliberately absent: they have no
            # BigQuery counterpart, so relying on them would make '' vs NULL
            # diverge between the two targets.
            echo "NULL AS '\\\\N'"
            if [[ -n "${BANKING_S3_REGION}" ]]; then
                echo "REGION '${BANKING_S3_REGION}'"
            fi
            echo ";"
            echo
        } >> "${TMP_SQL}"

        table_count=$((table_count + 1))
    done
done

{
    echo "COMMIT;"
} >> "${TMP_SQL}"

echo "Generated COPY script with ${table_count} tables: ${TMP_SQL}"
echo "Running against Redshift..."
echo

PGPASSWORD="${REDSHIFT_PASSWORD}" psql \
    --host="${REDSHIFT_HOST}" \
    --port="${REDSHIFT_PORT}" \
    --dbname="${REDSHIFT_DATABASE}" \
    --username="${REDSHIFT_USER}" \
    --set ON_ERROR_STOP=1 \
    --file="${TMP_SQL}"

echo
echo "Load complete. ${table_count} tables populated."
